import create from "zustand";

const useTicketStore = create((set) => ({
	pnr: "",
	isReturnFlight: "",
	flightNumber: "",
	ticketNumber: "",
	seatNumber: "",
	arrivalDate: "",
	arrivalTime: "",
	arrivalCityName: "",
	arrivalCountryCode: "",
	arrivalCountryName: "",
	departureDate: "",
	boardingTime: "",
	departureTime: "",
	departureCityName: "",
	departureCountryCode: "",
	checkInInfo: "",
	namePrefix: "",
	firstName: "",
	lastName: "",
	isLogged: false,

	setTicketInfo: (
		pnr,
		isReturnFlight,
		flightNumber,
		ticketNumber,
		seatNumber,
		arrivalDate,
		arrivalTime,
		arrivalCityName,
		arrivalCountryCode,
		arrivalCountryName,
		departureDate,
		boardingTime,
		departureTime,
		departureCityName,
		departureCountryCode,
		checkInInfo,
		namePrefix,
		firstName,
		lastName,
		isLogged
	) =>
		set((state) => ({
			pnr: pnr,
			isReturnFlight: isReturnFlight,
			flightNumber: flightNumber,
			ticketNumber: ticketNumber,
			seatNumber: seatNumber,
			arrivalDate: arrivalDate,
			arrivalTime: arrivalTime,
			arrivalCityName: arrivalCityName,
			arrivalCountryCode: arrivalCountryCode,
			arrivalCountryName:	arrivalCountryName,
			departureDate: departureDate,
			boardingTime: boardingTime,
			departureTime: departureTime,
			departureCityName: departureCityName,
			departureCountryCode: departureCountryCode,
			checkInInfo: checkInInfo,
			namePrefix: namePrefix,
			firstName: firstName,
			lastName: lastName,
			isLogged: isLogged,
		})),
}));

export default useTicketStore;
